cirrus_wheels_macos_arm64_task:
  name: Build macOS arm64 wheels. 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    CIBW_ARCHS_MACOS: arm64
    CIBW_BEFORE_ALL_MACOS: >
      python -m pip install wheel &&
      python setup.py package_assemble
    CIBW_SKIP: pp* cp38*
    CIBW_TEST_COMMAND: python -m regina.test
  install_pre_requirements_script:
    - brew install python3
    - python3 --version
  install_cibuildwheel_script:
    - python3 -m pip install cibuildwheel
  run_cibuildwheel_script:
    - python3 -m cibuildwheel --output-dir wheelhouse
  wheels_artifacts:
    path: "wheelhouse/*"
