name: Linux

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        python_version: [38, 39, 310, 311, 312, 313]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_ARCHS: auto64
          CIBW_PRERELEASE_PYTHONS: False
          CIBW_BUILD: cp${{ matrix.python_version }}-manylinux*
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y gmp-devel zlib-devel bzip2-devel
          CIBW_BEFORE_BUILD_LINUX:
            python setup.py package_assemble
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-cp${{ matrix.python_version }}-wheel
          path: ./wheelhouse/*.whl
