name: Linux with 3.8-3.10

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.2
        env:
          CIBW_BUILD: cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y gmp-devel zlib-devel bzip2-devel &&
            python setup.py package_assemble
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
