name: macOS with 3.11-3.13

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*
          # gmp already installed on macos runner
          CIBW_BEFORE_ALL_MACOS: >
            python -m pip install wheel setuptools &&
            python setup.py package_assemble &&
            ln -s /opt/homebrew/opt/gmp/include/gmp.h extinclude &&
            ln -s /opt/homebrew/opt/gmp/include/gmpxx.h extinclude &&
            ln -s /opt/homebrew/opt/gmp/lib/libgmp.a extlib &&
            ln -s /opt/homebrew/opt/gmp/lib/libgmpxx.a extlib
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
