name: macOS

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]
        # python_version: [38, 39, 310, 311, 312, 313]
        python_version: [38]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_PRERELEASE_PYTHONS: False
          CIBW_BUILD: cp${{ matrix.python_version }}-*
          CIBW_BEFORE_ALL_MACOS: >
            python -m pip install wheel setuptools &&
            python setup.py package_assemble &&
            bash build_gmp.sh
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-cp${{ python_version }}-wheel
          path: ./wheelhouse/*.whl
