name: macOS with 3.6-3.8

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64
          # gmp already installed on macos runner
          CIBW_BEFORE_ALL_MACOS: python setup.py package_assemble
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
