name: macOS with 3.8-3.10

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-*
          # gmp already installed on macos runner
          CIBW_BEFORE_ALL_MACOS: >
            python -m pip install wheel &&
            python setup.py package_assemble
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
